//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promatis.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Promatis.Core.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App domain &quot;{0}&quot; can&apos;t be unloaded.
        /// </summary>
        internal static string AppDomainHelper_AppDomainUnableUnload {
            get {
                return ResourceManager.GetString("AppDomainHelper_AppDomainUnableUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App domain &quot;{0}&quot; unloaded.
        /// </summary>
        internal static string AppDomainHelper_AppDomainUnloaded {
            get {
                return ResourceManager.GetString("AppDomainHelper_AppDomainUnloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Errors occurred while unloading the app domain &quot;{0}&quot;.
        /// </summary>
        internal static string AppDomainHelper_AppDomainUnloadError {
            get {
                return ResourceManager.GetString("AppDomainHelper_AppDomainUnloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assembly &quot;{0}&quot; was not loaded.
        /// </summary>
        internal static string AssemblyHelper_AssemblyNotLoaded {
            get {
                return ResourceManager.GetString("AssemblyHelper_AssemblyNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &quot;{0}&quot; is not found in arguments type.
        /// </summary>
        internal static string CommandLine_ArgumentNotFound {
            get {
                return ResourceManager.GetString("CommandLine_ArgumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &quot;{0}&quot; is duplicated.
        /// </summary>
        internal static string CommandLine_DuplicateArgument {
            get {
                return ResourceManager.GetString("CommandLine_DuplicateArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong position &quot;{1}&quot; on argument &quot;{0}&quot;.
        /// </summary>
        internal static string CommandLine_InvalidPositionsSequence {
            get {
                return ResourceManager.GetString("CommandLine_InvalidPositionsSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press any key for continue.
        /// </summary>
        internal static string CommandLine_PressAnyKey {
            get {
                return ResourceManager.GetString("CommandLine_PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Argument &quot;{0}&quot; is required, but it doesn&apos;t have value.
        /// </summary>
        internal static string CommandLine_RequiredArgumentIsNotSet {
            get {
                return ResourceManager.GetString("CommandLine_RequiredArgumentIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The instance &quot;{0}&quot; is not implements interface type &quot;{1}&quot;.
        /// </summary>
        internal static string Guard_InstanceNotImplementInterface {
            get {
                return ResourceManager.GetString("Guard_InstanceNotImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The instance &quot;{0}&quot; is not directly inherited from type &quot;{1}&quot;.
        /// </summary>
        internal static string Guard_InstanceNotInheritedOfType {
            get {
                return ResourceManager.GetString("Guard_InstanceNotInheritedOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type instance &quot;{0}&quot; is not equal &quot;{1}&quot;.
        /// </summary>
        internal static string Guard_InstanceNotOfType {
            get {
                return ResourceManager.GetString("Guard_InstanceNotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The instance &quot;{0}&quot; is not subclass of type &quot;{1}&quot;.
        /// </summary>
        internal static string Guard_InstanceNotSubclassOfType {
            get {
                return ResourceManager.GetString("Guard_InstanceNotSubclassOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The type &quot;{0}&quot; is not implements interface type &quot;{1}&quot;.
        /// </summary>
        internal static string Guard_TypeNotImplementInterface {
            get {
                return ResourceManager.GetString("Guard_TypeNotImplementInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The type &quot;{0}&quot; is not directly inherited from type &quot;{1}&quot;.
        /// </summary>
        internal static string Guard_TypeNotInheritedOfType {
            get {
                return ResourceManager.GetString("Guard_TypeNotInheritedOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SetValue of &quot;{0}&quot; can&apos;t be empty.
        /// </summary>
        internal static string Guard_ValueCantBeEmpty {
            get {
                return ResourceManager.GetString("Guard_ValueCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SetValue of &quot;{0}&quot; can&apos;t be undefined.
        /// </summary>
        internal static string Guard_ValueCantBeUndefined {
            get {
                return ResourceManager.GetString("Guard_ValueCantBeUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IoC context already initialized..
        /// </summary>
        internal static string IocContext_ContextAlreadyInitialized {
            get {
                return ResourceManager.GetString("IocContext_ContextAlreadyInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IoC ccontext is not initialized. Call Initialize method before..
        /// </summary>
        internal static string IocContext_ContextIsNotInitialized {
            get {
                return ResourceManager.GetString("IocContext_ContextIsNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation fail..
        /// </summary>
        internal static string OperationResult_FailMessage {
            get {
                return ResourceManager.GetString("OperationResult_FailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Operation success..
        /// </summary>
        internal static string OperationResult_SuccessMessage {
            get {
                return ResourceManager.GetString("OperationResult_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong format of encripted data.
        /// </summary>
        internal static string StringExtensions_WrongEncryptedData {
            get {
                return ResourceManager.GetString("StringExtensions_WrongEncryptedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must define error message.
        /// </summary>
        internal static string YouMustDefineErrorMessage {
            get {
                return ResourceManager.GetString("YouMustDefineErrorMessage", resourceCulture);
            }
        }
    }
}
